    <div class="array_date" data-iteam="<?php echo  $bestsell_book?>" style="display: none;" >
        <?php echo  $sell_book_key?>
    </div>
     <div class="inventory_book"  data-iteam="<?php echo  $inventory_book ?>" style="display: none;" value="">
        <?php echo  $inventory_book_key?>
    </div>
    <div class="data_value"  data-iteam="<?php echo  $soldout_book_value ?>" style="display: none;" value="">
        <?php echo  $soldout_book_key?>
    </div>
	 <div class="row mt20">
        <div  class="col-sm-1 mb30" >
            
        </div>
        <div class="col-sm-10 mb30">
        <canvas id="hourly-canvas-6"></canvas>
        <p class="col-lg-12 text-label-center  font-text "  style="font-size:17px; 
        margin-top: 30px; margin-bottom: -12px;">
                Biểu đồ thống kê số lượng sách bán chạy </p>
        </div>
    </div>
    <div class="row mt20">
      <div class="col-sm-8">
            <canvas id="hourly-canvas-3"></canvas>
            <div class="row mt50">
                <p class="col-lg-12 text-label-center  font-text "  style="font-size:17px">
                Biểu đồ thống kê số lượng sách không bán được</p>
            </div>
        </div>

        <div class="col-sm-4">
            <canvas id="hourly-canvas-4"></canvas>
            <div class="row mt50">
                <p class="col-lg-12 text-label-center  font-text "  style="font-size:17px;margin-top: 17px;">
                Biểu đồ thống kê số lượng sách hết</p>
            </div>
        </div>
    </div>
