		
        <div class="array_date" style="display: none;" >
			<?php echo  $data_date?>	
		</div>
	   <div class="data_value" style="display: none;" value="">
            <?php echo  $data_value?>
        </div>
		<div class="row mt20">
    			<div class="col-sm-2">
    			</div>

    		    <div class="col-sm-8 mb30">
    		        <canvas id="hourly-canvas-2"></canvas>
    		    </div>

    		    <div class="col-sm-2">
    			</div>
		</div>
		<div class="row">
    			<p class="col-lg-12 text-label-center  font-text ">
    			Biểu đồ thống kê doanh thu theo ngày, tháng, năm </p>
		</div>
