
<div class="page-header">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-8">
                <div class="page-header-title">
                    <h4 class="m-b-10">Dashboard</h4>
                </div>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="index.html">
                            <i class="feather icon-home"></i>
                        </a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="#!">Dashboard</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="pcoded-inner-content">
    <div class="main-body">
        <div class="page-wrapper">
            <div class="page-body">
                <!-- [ page content ] start -->
                <div class="row">

                    <!-- customar project  start -->
                    <div class="col-xl-3 col-md-6">
                        <div class="card">
                            <div class="card-block">
                                <div class="row align-items-center m-l-0">
                                    <div class="col-auto">
                                        <i class="icon feather icon-book f-30 text-c-purple"></i>
                                    </div>
                                    <div class="col-auto">
                                        <h6 class="text-muted m-b-10">SL Sách Còn Lại</h6>
                                        <h2 class="m-b-0"><?= $total_book ?></h2>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-md-6">
                        <div class="card">
                            <div class="card-block">
                                <div class="row align-items-center m-l-0">
                                    <div class="col-auto">
                                        <i class="icon feather icon-navigation-2 f-30 text-c-green"></i>
                                    </div>
                                    <div class="col-auto">
                                        <h6 class="text-muted m-b-10">Tổng Hóa Đơn</h6>
                                        <h2 class="m-b-0"><?= $count_bill ?></h2>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-md-6">
                        <div class="card">
                            <div class="card-block">
                                <div class="row align-items-center m-l-0">
                                    <div class="col-auto">
                                        <i class="icon feather icon-users f-30 text-c-red"></i>
                                    </div>
                                    <div class="col-auto">
                                        <h6 class="text-muted m-b-10">SL Khách Hàng </h6>
                                        <h2 class="m-b-0"><?= $count_bill ?></h2>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-md-6">
                        <div class="card">
                            <div class="card-block">
                                <div class="row align-items-center m-l-0">
                                    <div class="col-auto">
                                        <i class="icon feather icon-award f-30 text-c-blue"></i>
                                    </div>
                                    <div class="col-auto">
                                        <h6 class="text-muted m-b-10">SL Sách Bán Được</h6>
                                        <h2 class="m-b-0"><?= $book_sold ?></h2>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- customar project  end -->
                    <div class="col-xl-10 col-md-12" style="margin-left: 98px">
                        <div class="card latest-update-card" style="border-radius: 4.25rem;background-color: #fff800;">
                            <div class="card-header">
                                <h2 class="font-text font-da-cursive text-label-center">Thời Gian Cập Nhật Hóa Đơn</h2>
                                <div class="card-header-right"> 
                                    <ul class="list-unstyled card-option">
                                        <li class="first-opt"><i class="feather icon-chevron-left open-card-option"></i></li>
                                        <li><i class="feather icon-maximize full-card"></i></li>
                                        <li><i class="feather icon-minus minimize-card"></i></li>
                                        <li><i class="feather icon-refresh-cw reload-card"></i></li>
                                        <li><i class="feather icon-trash close-card"></i></li>
                                        <li><i class="feather icon-chevron-left open-card-option"></i></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="card-block">
                                <div class="latest-update-box">
                                   <!--  <div class="row p-t-20 p-b-30">
                                        <div class="col-auto text-right update-meta">
                                            <p class="text-muted m-b-0 d-inline">4 hrs ago</p>
                                            <i class="feather icon-briefcase bg-c-red update-icon"></i>
                                        </div>
                                        <div class="col">
                                            <h6>+ 5 New Products were added!</h6>
                                            <p class="text-muted m-b-0">Congratulations!</p>
                                        </div>
                                    </div> -->
                                    <?php foreach ($bill as $key => $value) {
                                     ?>
                                    <div class="row p-b-30">
                                        <div class="col-auto text-label-center update-meta">
                                            <!-- <p class="text-muted m-b-0 d-inline">1 day ago</p> -->
                                            <time class="text-muted m-b-0 d-inline timeago" datetime="<?php echo $key ?>">
                                                 July 17, 2008
                                            </time>
                                            <i class="feather icon-check f-w-600 bg-c-green update-icon"></i>
                                        </div>
                                        <div class="col font-da-cursive ">
                                            <a href="/bookstore-m/bills/detail/<?php echo $value['id']  ?>" ><h5 style="font-size: 1.2rem;"  >+ <b style="    color: deepskyblue; font-size: xx-large;">
                                                    <?php echo $value['book_count'] ?></b> Sách mới được thêm vào hóa đơn !
                                            </h5></a>
                                            <p class="text-muted m-b-0"> Được tạo bởi <strong><?php echo $value['created_by'] ?></strong></p>
                                        </div>
                                    </div>
                                    <?php } ?>
                                    <!-- <div class="row p-b-0">
                                        <div class="col-auto text-right update-meta">
                                            <p class="text-muted m-b-0 d-inline">2 day ago</p>
                                            <i class="feather icon-facebook bg-facebook update-icon"></i>
                                        </div>
                                        <div class="col">
                                            <h6>+2 Friend Requests</h6>
                                            <p class="text-muted m-b-10">This is great, keep it up!</p>
                                            <div class="table-responsive">
                                                <table class="table table-hover">
                                                    <tbody>
                                                        <tr>
                                                            <td class="b-none">
                                                                <a href="#!" class="align-middle">
                                                                    <img src="../files/assets/images/avatar-2.jpg" alt="user image" class="img-radius img-40 align-top m-r-15">
                                                                    <div class="d-inline-block">
                                                                        <h6>Jeny William</h6>
                                                                        <p class="text-muted m-b-0">Graphic Designer</p>
                                                                    </div>
                                                                </a>
                                                            </td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div> -->
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- prject ,team member start -->
                   <!--  <div class="col-xl-7 col-md-12">
                        <div class="card table-card">
                            <div class="card-header">
                                <h5>Projects</h5>
                                <div class="card-header-right">
                                    <ul class="list-unstyled card-option">
                                        <li class="first-opt"><i class="feather icon-chevron-left open-card-option"></i></li>
                                        <li><i class="feather icon-maximize full-card"></i></li>
                                        <li><i class="feather icon-minus minimize-card"></i></li>
                                        <li><i class="feather icon-refresh-cw reload-card"></i></li>
                                        <li><i class="feather icon-trash close-card"></i></li>
                                        <li><i class="feather icon-chevron-left open-card-option"></i></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="card-block">
                                <div class="table-responsive">
                                    <table class="table table-hover">
                                        <thead>
                                            <tr>
                                                <th>
                                                    <div class="chk-option">
                                                        <div class="checkbox-fade fade-in-primary">
                                                            <label class="check-task">
                                                                <input type="checkbox" id="selectall"/>
                                                                <span class="cr">
                                                                    <i class="cr-icon feather icon-check f-w-600 txt-default"></i>
                                                                </span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    Assigned</th>
                                                <th>Name</th>
                                                <th>Due Date</th>
                                                <th class="text-right">Priority</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>
                                                    <div class="chk-option">
                                                        <div class="checkbox-fade fade-in-primary">
                                                            <label class="check-task">
                                                                    <input type="checkbox" class="case" name="case" value="1"/>
                                                                    <span class="cr">
                                                                        <i class="cr-icon feather icon-check f-w-600 txt-default"></i>
                                                                    </span>
                                                                </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-inline-block align-middle">
                                                        <img src="../files/assets/images/avatar-4.jpg" alt="user image" class="img-radius img-40 align-top m-r-15">
                                                        <div class="d-inline-block">
                                                            <h6>John Deo</h6>
                                                            <p class="text-muted m-b-0">Graphics Designer</p>
                                                        </div>
                                                    </div>
                                                </td>
                                                <td>Able Pro</td>
                                                <td>Jun, 26</td>
                                                <td class="text-right"><label class="label label-danger">Low</label></td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="chk-option">
                                                        <div class="checkbox-fade fade-in-primary">
                                                            <label class="check-task">
                                                                    <input type="checkbox" class="case" name="case" value="2"/>
                                                                    <span class="cr">
                                                                        <i class="cr-icon feather icon-check f-w-600 txt-default"></i>
                                                                    </span>
                                                                </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-inline-block align-middle">
                                                        <img src="../files/assets/images/avatar-2.jpg" alt="user image" class="img-radius img-40 align-top m-r-15">
                                                        <div class="d-inline-block">
                                                            <h6>Jenifer Vintage</h6>
                                                            <p class="text-muted m-b-0">Web Designer</p>
                                                        </div>
                                                    </div>
                                                </td>
                                                <td>Mashable</td>
                                                <td>March, 31</td>
                                                <td class="text-right"><label class="label label-primary">high</label></td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="chk-option">
                                                        <div class="checkbox-fade fade-in-primary">
                                                            <label class="check-task">
                                                                    <input type="checkbox" class="case" name="case" value="3"/>
                                                                    <span class="cr">
                                                                        <i class="cr-icon feather icon-check f-w-600 txt-default"></i>
                                                                    </span>
                                                                </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-inline-block align-middle">
                                                        <img src="../files/assets/images/avatar-3.jpg" alt="user image" class="img-radius img-40 align-top m-r-15">
                                                        <div class="d-inline-block">
                                                            <h6>William Jem</h6>
                                                            <p class="text-muted m-b-0">Developer</p>
                                                        </div>
                                                    </div>
                                                </td>
                                                <td>Flatable</td>
                                                <td>Aug, 02</td>
                                                <td class="text-right"><label class="label label-success">medium</label></td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <div class="chk-option">
                                                        <div class="checkbox-fade fade-in-primary">
                                                            <label class="check-task">
                                                                    <input type="checkbox" class="case" name="case" value="4"/>
                                                                    <span class="cr">
                                                                        <i class="cr-icon feather icon-check f-w-600 txt-default"></i>
                                                                    </span>
                                                                </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-inline-block align-middle">
                                                        <img src="../files/assets/images/avatar-2.jpg" alt="user image" class="img-radius img-40 align-top m-r-15">
                                                        <div class="d-inline-block">
                                                            <h6>David Jones</h6>
                                                            <p class="text-muted m-b-0">Developer</p>
                                                        </div>
                                                    </div>
                                                </td>
                                                <td>Guruable</td>
                                                <td>Sep, 22</td>
                                                <td class="text-right"><label class="label label-primary">high</label></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                    <div class="text-right m-r-20">
                                        <a href="#!" class=" b-b-primary text-primary">View all Projects</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
 -->
                    <!-- Active Tickets, Latest Posts end -->

                </div>
                <!-- [ page content ] end -->
            </div>
        </div>
    </div>
</div>

