<div class="page-header">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-8">
                <div class="page-header-title">
                    <h4 class="m-b-10">Quản Lý Báo Cáo
                    </h4>
                </div>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="index.html">
                            <i class="feather icon-home"></i>
                        </a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="#!">Quản Lý Báo Cáo</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="pcoded-inner-content">
    <div class="main-body">

        <div class="page-wrapper">
        <div class="page-body">
            <!-- [ page content ] start -->
            <div class="row">

                <!-- site Analytics card start -->

                <div class="col-lg-12 col-md-12">
                    <div class="card">
                        <div class="card-header font-text font-faauto ">
                            <h2>Báo Cáo Doanh Thu</h2>
                            <p><?php $this->flashSession->output(); ?></p>
                        </div>
                           <form  action="<?php echo $this->url->get('report/filterbills') ?>" id="filter-data" method="post" class="form-search form">
                                     <div class="row">
                                      
                                        <div class="ml50 mt15 mb15 col-sm-3 font-text" >
                                            <label for="">Từ ngày</label>
                                            <input class="form-control date-start date1" type="date" name="start" value="<?php echo $start ?>">
                                        </div>
                                        <div class=" mt15 mb15 ml50 col-sm-3 font-text">
                                            <label for="">Đến ngày</label>
                                            <input class="form-control date-end date1" type="date" name="end" value="<?php echo $end ?>">
                                        </div>
                                        <div class=" mt15 mb15 ml50 col-sm-3 ">
                                             <label for="">Nhân viên:</label>
            
                                        <!-- <label class="col-sm-4 col-form-label text-label-right  font-text">Nhân viên:</label> -->
                                            <!-- <div class="form-control"> -->
                                                <select name="teacher" class="browser-default custom-select">
                                                    <option value="">---Chọn nhân viên---</option>
                                                    <?php foreach($nhanvien as $key => $val) {?>
                                                        <option value="<?= $val->code ?>" <?php echo $val->code == $nhanvien ? 'selected' :''?>> <?= $val->fullname ?></option>
                                                    <?php }?>
                                                </select>
                                            <!-- </div> -->
                                        </div>
                                    </div>
                                    <div class="clearfix mb20 mr50">
                                        <div class="pull-right">
                                            <!-- <a href="" class="btn btn-primary btn-sm">Xem báo cáo</a> -->
                                             <button type="submit" class="btn btn-primary btn-sm">Xem báo cáo</button>
                                        </div>
                                    </div>
                            </form>
                        <div class="card-block">
                            <div class="array_date" style="display: none;" ><?php echo  $array_date?></div>
                               <div class="data_value" style="display: none;" value=""><?php echo  $data_value?></div>
                        	<div class="row mt20">
                        		<div class="col-sm-2">
                        		</div>

                                <div class="col-sm-8 mb30">
                                    <canvas id="hourly-canvas-2"></canvas>
                                </div>

                                <div class="col-sm-2">
                        		</div>
                            </div>
                            <div class="row">
                            	<p class="col-lg-12 text-label-center  font-text ">
                            	Biểu đồ thống kê doanh thu theo ngày, tháng, năm </p>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                <!-- <table id="dom-table" class="table table-striped table-bordered nowrap dataTable" role="grid" aria-describedby="simpletable_info">
                                    <thead>
                                        <tr role="row">

                                            <th class="sorting_disabled" rowspan="1" colspan="1">STT</th>
                                            <th class="sorting_disabled" rowspan="1" colspan="1">Mã hóa đơn</th>
                                            <th class="sorting_disabled" rowspan="1" colspan="1">Tên khách hàng</th>
                                            <th class="sorting_disabled" rowspan="1" colspan="1">Loại sách</th>
                                            <th class="sorting_disabled" rowspan="1" colspan="1">Tên sách</th>
                                            <th class="sorting_disabled" rowspan="1" colspan="1"> Ngày tạo</th>
                                            <th class="sorting_disabled" rowspan="1" colspan="3">Tùy Chọn</th>
                                        </tr>
                                    </thead>
                                    <tbody>

                                    </tbody>
                                </table> -->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

