<div class="page-header">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-8">
                <div class="page-header-title">
                    <h4 class="m-b-10">Quản Lý Báo Cáo
                    </h4>
                </div>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="index.html">
                            <i class="feather icon-home"></i>
                        </a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="#!">Quản Lý Báo Cáo</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="pcoded-inner-content">
    <div class="main-body">

        <div class="page-wrapper">
        <div class="page-body">
            <!-- [ page content ] start -->
            <div class="row">

                <!-- site Analytics card start -->

                <div class="col-lg-12 col-md-12">
                    <div class="card">
                        <div class="card-header font-text font-faauto ">
                            <h2>Báo Cáo Thống Kê Sách </h2>
                            <p><?php $this->flashSession->output(); ?></p>
                        </div>
                      <form  action="<?php echo $this->url->get('reports/filterbooks') ?>" id="filter-data" method="post" class="form-search form load_book_report">
                                 <div class="row">
                                    <div class=" ml30 mb15 col-sm-1 font-text" >
                                   
                                    </div>
                                    <div class=" mt15 mb15 col-sm-3 font-text" >
                                        <label for="">Từ ngày</label>
                                        <input class="form-control date-start date1" type="date" name="start" value="<?php echo $start ?>">
                                    </div>
                                    <div class=" mt15 mb15 ml50 col-sm-3 font-text">
                                        <label for="">Đến ngày</label>
                                        <input class="form-control date-end date1" type="date" name="end" value="<?php echo $end ?>">
                                    </div>
                                </div>
                                <div class="clearfix mb20 mr50">
                                    <div class="pull-right">
                                         <button type="submit" class="btn btn-primary btn-sm ">Xem báo cáo</button>
                                    </div>
                                </div>
                        </form>
                        <div class="card-block">
                            <div class="render-filter">
                            <div class="array_date" data-iteam="<?php echo  $bestsell_book?>" style="display: none;" >
                                <?php echo  $sell_book_key?>
                            </div>
                             <div class="inventory_book"  data-iteam="<?php echo  $inventory_book ?>" style="display: none;" value="">
                                <?php echo  $inventory_book_key?>
                            </div>
                            <div class="data_value"  data-iteam="<?php echo  $soldout_book_value ?>" style="display: none;" value="">
                                <?php echo  $soldout_book_key?>
                            </div>
                                <div class="row mt20">
                                    <div  class="col-sm-1 mb30" >
                                        
                                    </div>
                                    <div class="col-sm-10 mb30">
                                    <canvas id="hourly-canvas-6"></canvas>
                                    <p class="col-lg-12 text-label-center  font-text "  style="font-size:17px; 
                                    margin-top: 30px; margin-bottom: -12px;">
                                            Biểu đồ thống kê số lượng sách bán chạy </p>
                                    </div>
                                </div>
                            	<div class="row mt20">
                                  <div class="col-sm-8">
                                        <canvas id="hourly-canvas-3"></canvas>
                                        <div class="row mt50">
                                            <p class="col-lg-12 text-label-center  font-text "  style="font-size:17px">
                                            Biểu đồ thống kê số lượng sách không bán được</p>
                                        </div>
                                    </div>

                                    <div class="col-sm-4">
                                        <canvas id="hourly-canvas-4"></canvas>
                                        <div class="row mt50">
                                            <p class="col-lg-12 text-label-center  font-text "  style="font-size:17px;margin-top: 17px;">
                                            Biểu đồ thống kê số lượng sách hết</p>
                                        </div>
                                    </div>
                                </div>
                               <!--  <div class="row mt20">
                                    <div class="col-sm-2">

                                    </div>
                                    <div class="col-sm-8">
                                        <canvas id="hourly-canvas-3"></canvas>
                                        <div class="row mt50">
                                            <p class="col-lg-12 text-label-center  font-text "  style="font-size:17px">
                                            Biểu đồ thống kê số lượng sách không bán được</p>
                                        </div>
                                    </div>
                                </div> -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

